### ISSUE TITLE
bug group_by

### ISSUE THREAD

**Issue by desrousseaux** [139bercy/secret_stat#14]
gb = [
    ("CODE_REGION", "CODE_DEPARTEMENT"),
    ("MESURE", "FILIÈRE"),
    ("MESURE", "TYPE_ENTREPRISE"),
]

col_secret = [
    "MONTANT_INVESTISSEMENT",
    "MONTANT_PARTICIPATION_ETAT"
]

donne l'erreur suivante : 
KeyError                                  Traceback (most recent call last)
<ipython-input-48-45b181313256> in <module>
----> 1 x = apply_secret_stat(group_by=gb,
      2                       columns_apply_secret=col_secret,
      3                       column_to_check="CODE_REGION",
      4                       dataframe=df,
      5                      export_to_csv=True)

~/Projects/secret_stat/main.py in apply_secret_stat(group_by, columns_apply_secret, column_to_check, data_path, sep, dataframe, export_to_csv, path_to_export)
     30 
     31     # Test the multiple aggregation
---> 32     final_masked_dict = specific_aggregator.specific_aggregator_factory(df_entreprises, group_by,
     33                                                                         columns_apply_secret)
     34 

~/Projects/secret_stat/aggregation.py in specific_aggregator_factory(self, df, group_by, columns_apply_secret)
     33     def specific_aggregator_factory(self, df: pd.DataFrame, group_by: list, columns_apply_secret: list) -> pd.DataFrame:
     34         version_3 = self.perform_multiple_safe_aggregation(df, group_by)
---> 35         dict_masked_secondary = self.check_and_apply_secondary_secret(version_3,
     36                                                                       group_by,
     37                                                                       columns_apply_secret,

~/Projects/secret_stat/aggregation.py in check_and_apply_secondary_secret(self, df_dict, gb_keys, columns_apply_secret, verbose)
    265 
    266         disclosure_df_0 = self._get_full_disclosion_df(df_0)
--> 267         disclosure_df_1 = self._get_full_disclosion_df(df_1)
    268 
    269         for column_name in self.relevant_column:

~/Projects/secret_stat/aggregation.py in _get_full_disclosion_df(self, init_df)
    196 
    197         for column_name in self.relevant_column:
--> 198             df_grouped = self._compute_columns_secondary_secret(init_df,
    199                                                                 [self.common_column, column_name + '_keep'])
    200 

~/Projects/secret_stat/aggregation.py in _compute_columns_secondary_secret(self, df, column_names)
    168                             for (col_lvl2, func) in LIST_FUNCTIONS}
    169 
--> 170         grouped_df = df.groupby(column_names,
    171                                 as_index=False).agg(aggregation_dict)
    172         return grouped_df

~/anaconda3/envs/secret_stat/lib/python3.8/site-packages/pandas/core/frame.py in groupby(self, by, axis, level, as_index, sort, group_keys, squeeze, observed, dropna)
   6712         axis = self._get_axis_number(axis)
   6713 
-> 6714         return DataFrameGroupBy(
   6715             obj=self,
   6716             keys=by,

~/anaconda3/envs/secret_stat/lib/python3.8/site-packages/pandas/core/groupby/groupby.py in __init__(self, obj, keys, axis, level, grouper, exclusions, selection, as_index, sort, group_keys, squeeze, observed, mutated, dropna)
    558             from pandas.core.groupby.grouper import get_grouper
    559 
--> 560             grouper, exclusions, obj = get_grouper(
    561                 obj,
    562                 keys,

~/anaconda3/envs/secret_stat/lib/python3.8/site-packages/pandas/core/groupby/grouper.py in get_grouper(obj, key, axis, level, sort, observed, mutated, validate, dropna)
    814                 in_axis, name, level, gpr = False, None, gpr, None
    815             else:
--> 816                 raise KeyError(gpr)
    817         elif isinstance(gpr, Grouper) and gpr.key is not None:
    818             # Add key to exclusions

KeyError: 'CODE_REGION'

**Comment by kaa-serpent** [comment]
Si je ne dis pas de bêtises l'erreur provient simplement du fait que dans les données fournies la colonne 'CODE_REGION' n'existe pas.

**Comment by kaa-serpent** [comment]
_compute_columns_secondary_secret() essaie de groupby avec la colonne à checker
